# Generated by Django 4.1.4 on 2022-12-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_contactus_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
