# Generated by Django 4.1.4 on 2022-12-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_contactus_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='RecievedMail',
        ),
        migrations.RenameModel(
            old_name='MailMassage',
            new_name='SentMail',
        ),
    ]
